name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Make environment setup script executable
      run: chomod +x ./environmentSetup.sh
    - name: Set up environment
      run: ./environmentSetup.sh ${{ secrets.Artifactory_URL }} ${{ secrets.Artifactory_REPO }} ${{ secrets.Artifactory_USER }} ${{ secrets.Artifactory_PASSWORD }}
    - name: Build with Gradle
      run: ./gradlew build
    - name: Run unit tests
      run: ./gradlew test
